sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "10.9"

before_script:
  - echo "$FIREBASE_TOKEN"
  - npm install -g @angular/cli
  - npm install -g firebase-tools

script:
  - ng build --prod --aot

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
    