sudo: required

branches:
  only:
  - master
  - develop

addons:
  chrome: stable

language: node_js
node_js:
  - "10.16.1"

before_script:
  - cd src/client
  - npm install
  - npm install -g @angular/cli
  - npm install -g firebase-tools

script:
  - ng build --prod --aot

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master
    all_branches: false
