# safelist
branches:
  only:
  - master
  - feature/NE-31-travis-ci

dist: trusty
sudo: false

language: node_js
node_js:
  - '8'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_install:
  - gem install bundler --pre
  - npm install -g firebase-tools

install:
  - npm install

script:
  - npm run build --prod