# safelist
branches:
  only:
  - master
  - feature/NE-31-travis-ci

dist: trusty
sudo: false

language: node_js
node_js:
  - '8'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_install:
  - gem uninstall bundler
  - gem install bundler --version '1.17.3'  

install:
  - npm install
  - npm install -g firebase-tools

script:
  - npm run build --prod