# safelist
branches:
  only:
  - master
  - feature/NE-31-travis-ci

dist: trusty
sudo: required

language: node_js
node_js:
  - '10'

before_install:
  - gem uninstall bundler
  - gem install bundler --version '1.17.3'  

before_script:
  - npm install
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod