sudo: required

# safelist
branches:
  only:
  - master
  - develop

addons:
  chrome: stable

language: node_js
node_js:
  - "10.9"

before_script:
  - echo "Test Travis CI"
  - npm install -g @angular/cli
  - npm install -g firebase-tools

script:
  - ng build --prod --aot

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  on:
    all_branches: true
